[package]
name = "project"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
axum = "0.7"
tower-http = { version = "0.6.6", features = ["fs"] }
serde = {version = "1.0.219" , features = ["derive"]}
